apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: bus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bus
    spec:
      containers:
      - name: bus
        image: docker.io/dkimot/jumprope-bus
        env:
        - name: NODE_ENV
          value: 'production'
