apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: logger
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: docker.io/dkimot/jumprope-logger
