apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
      - name: router
        image: docker.io/dkimot/jumprope-router
        env:
        - name: NODE_ENV
          value: 'production'
